/mqtt-exporter # python3 main.py
Serial Port /dev/ACM0 is opened
 Connected with result code: 0
Serial Data: [#] 29.50;0
Tipo b'0' valor b'29.50'
Sending to  temp_c_server value b'29.50'
Done
 [Topic: temp_c_server] b'29.50'
         Topic: temp_c_server
         Payload: 29.5
Serial Data: [#] 91.0;2
Tipo b'2' valor b'91.0'
Sending to  temp_f_server value b'91.0'
Done
 [Topic: temp_f_server] b'91.0'
         Topic: temp_f_server
         Payload: 91.0
Serial Data: [#] 29.50;0
Tipo b'0' valor b'29.50'
Sending to  temp_c_server value b'29.50'
Done
 [Topic: temp_c_server] b'29.50'
         Topic: temp_c_server
         Payload: 29.5
Serial Data: [#] 91.0;2
Tipo b'2' valor b'91.0'
Sending to  temp_f_server value b'91.0'
Done
 [Topic: temp_f_server] b'91.0'
         Topic: temp_f_server
         Payload: 91.0
Serial Data: [#] 29.50;0
Tipo b'0' valor b'29.50'
Sending to  temp_c_server value b'29.50'
Done
Serial Data: [#] 91.0;2
Tipo b'2' valor b'91.0'
Sending to  temp_f_server value b'91.0'
Done
 [Topic: temp_c_server] b'29.50'
         Topic: temp_c_server
         Payload: 29.5
 [Topic: temp_f_server] b'91.0'
         Topic: temp_f_server
         Payload: 91.0
Traceback (most recent call last):
  File "/mqtt-exporter/main.py", line 279, in <module>
    main()
  File "/mqtt-exporter/main.py", line 241, in main
    line = ser.readline()
  File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
/mqtt-exporter # 

